let tilesize = 32;
let levels = [
  ["wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww  wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwhhwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
   "w                                                                     wwwwwwwwwwwwwwwwww                                       w",
   "w    w                                                                wwwwwwwwwwwwwwwwww                                       w",
   "w    w                                                                wwwwwwwwwwwwwwwwww                                       w",
   "w    w                                                                wwwwwwwwwwwwwwwwww                                       w",
   "w    ww                                                               wwwwwwwwwwwwwwwwww                                       w",
   "w    w                                      ttt                       wwwwwwwwwwwwwwwwww                                       w",
   "w    wwwww                                  t t                       wwwwwwwwwwwwwwwwww                                       w",
   "w    w       s                         w stwtwt                       wwwwwwwwwwwwwwwwww                                       w",
   "w    wcccccccc                              ttt                       wwwwwwwwwwwwwwwwww                                       w",
   "w    wwwwwwwww                                                        wwwwwwwwwwwwwwwwww                                       w",
   "w                 p            t                                      wwwwwwwwwwwwwwwwww                                       w",
   "w                 w ccc s    wtt                                      wwwwwwwwwwwwwwwwww                                       w",
   "w            s    wwwwwwwwwwwwtt                                      wwwwwwwwwwwwwwwwww                                       w",
   "w    www     w                                                        wwwwwwwwwwwwwwwwww                                       w",
   "w    www     w                        s                               wwwwwwwwwwwwwwwwww                                       w",
   "w    www     w                        s                               wwwwwwwwwwwwwwwwww                  ph     Bb            w",
   "w              wwwwwww                s                               wwwwwwwwwwwwwwwwww                  www    bb            w",
   "w    www         w                    s                               wwwwwwwwwwwwwwwwww                 wwwww                 w",
   "w                                                                     wwwwwwwwwwwwwwwwww               wwwwwwwww               w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww  wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                 s                                                                  wwwwwwwwwwwww             w",
   "w                                 s                                                                  wwwwwwwwwwwww             w",
   "w                                 s                                   wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
  ]
];
