let tilesize = 32;
let levels = [
  ["wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
   "w                                 w",
   "w    w                            w",
   "w    w                            w",
   "w    w                            w",
   "w    ww                           w",
   "w    w                            w",
   "w    wwwww                        w",
   "w    w       s                    w",
   "w    w                            w",
   "w    wwwwwwwww                    w",
   "w                 p               w",
   "w                 w     s    w    w",
   "w            s    wwwwwwwwwwww    w",
   "w    www     w                    w",
   "w    www     w                    w",
   "w    www     w                    w",
   "w              wwwwwww            w",
   "w    www         w                w",
   "w                                 w",
   "w                                 w",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",]
];