let tilesize = 32;
let levels = [
  ["wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww  wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww  wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
   "w                                                                     wwwwwwwwwwwwwwwwww                                       w",
   "w    w                                                                wwwwwwwwwwwwwwwwww                                       w",
   "w    w                                                                wwwwwwwwwwwwwwwwww                                       w",
   "w    w                                                                wwwwwwwwwwwwwwwwww                                       w",
   "w    ww                                                               wwwwwwwwwwwwwwwwww                                       w",
   "w    w                                                                wwwwwwwwwwwwwwwwww                                       w",
   "w    wwwww                                                            wwwwwwwwwwwwwwwwww                                       w",
   "w    w       s                                                        wwwwwwwwwwwwwwwwww                                       w",
   "w    wcccccccc                                                        wwwwwwwwwwwwwwwwww                                       w",
   "w    wwwwwwwww                                                        wwwwwwwwwwwwwwwwww                                       w",
   "w                 p          t                            Bb          wwwwwwwwwwwwwwwwww                                       w",
   "w                 w ccc s    wtt                          bb          wwwwwwwwwwwwwwwwww                                       w",
   "w            s    wwwwwwwwwwwwtt                                      wwwwwwwwwwwwwwwwww                                       w",
   "w    www     w                                                        wwwwwwwwwwwwwwwwww                                       w",
   "w    www     w                                                        wwwwwwwwwwwwwwwwww                                       w",
   "w    www     w                                                        wwwwwwwwwwwwwwwwww                                       w",
   "w              wwwwwww                                                wwwwwwwwwwwwwwwwww                   w                   w",
   "w    www         w                                                    wwwwwwwwwwwwwwwwww                  www                  w",
   "w                                                                     wwwwwwwwwwwwwwwwww                wwwwwww                w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww  wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "w                                                                                                    wwwwwwwwwwwww             w",
   "w                                                                                                    wwwwwwwwwwwww             w",
   "w                                                                     wwwwwwwwwwwwwwwwww             wwwwwwwwwwwww             w",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
  ]
];
